/**
 * Failenn's dither — each preset sets `renderStyle` + slider defaults.
 * Dropdown order is alphabetical by `label` (see populatePresets in sketch.js).
 *
 * renderStyle: organic | organic_dots | halftone | stipple | halftone_edges |
 *   diamond_overlay | ordered8 | threshold | fs | atkinson | jarvis | stucki | burkes | sierra2
 */
const DITHER_PRESETS = {
  custom: {
    label: "Custom",
    renderStyle: "organic",
  },

  organic_dot_field_adaptive21: {
    label: "Adaptive Dot Field 21",
    renderStyle: "organic_dots",
    gridCount: 56,
    minRadius: 1.5,
    maxRadius: 13,
    bridgeScale: 3.77,
    bridgeWaist: 0.1,
    maxConnectDist: 1.2,
    toneDiffLimit: 0.15,
    gradientThreshold: 0.13,
    edgeTaper: 0.35,
    maxBright: 0.5,
    maxLinksPerDot: 0,
    contrast: 1.1,
    quantizeLevels: 0,
  },

  atkinson: {
    label: "Atkinson (Crunchy Newspaper)",
    renderStyle: "atkinson",
    gridCount: 140,
    contrast: 1.1,
    quantizeLevels: 2,
    halftoneGamma: 1,
    edgeTaper: 0,
  },

  ordered_bayer8: {
    label: "Bayer 8×8 (Finer)",
    renderStyle: "ordered8",
    contrast: 1.02,
  },

  burkes: {
    label: "Burkes",
    renderStyle: "burkes",
    gridCount: 140,
    contrast: 1.0,
    quantizeLevels: 2,
    halftoneGamma: 1,
    edgeTaper: 0,
  },

  contrast_based_dither: {
    label: "Floyd–Steinberg + Punch",
    renderStyle: "fs",
    gridCount: 140,
    contrast: 1.55,
    quantizeLevels: 2,
    halftoneGamma: 1,
    edgeTaper: 0,
  },

  square_overlay_default: {
    label: "Square Overlay",
    renderStyle: "square_overlay",
    gridCount: 72,
    minRadius: 0.5,
    maxRadius: 14,
    bridgeScale: 3.77,
    bridgeWaist: 0.1,
    maxConnectDist: 1.2,
    toneDiffLimit: 0.15,
    gradientThreshold: 0.12,
    edgeTaper: 0.35,
    maxBright: 0.96,
    maxLinksPerDot: 2,
    contrast: 1.12,
    quantizeLevels: 0,
    stippleJitter: 0.45,
    halftoneGamma: 0.82,
    edgeMag: 0.14,
  },

  concentric_default: {
    label: "Concentric Rings",
    renderStyle: "concentric",
    gridCount: 48,
    minRadius: 1,
    maxRadius: 18,
    bridgeScale: 1.2,
    bridgeWaist: 0.6,
    contrast: 1.1,
    halftoneGamma: 0.85,
    stippleJitter: 0,
    quantizeLevels: 0,
  },

  diamond_overlay_noise: {
    label: "Diamond Overlay",
    renderStyle: "diamond_overlay",
    gridCount: 72,
    minRadius: 0.5,
    maxRadius: 14,
    bridgeScale: 3.77,
    bridgeWaist: 0.1,
    maxConnectDist: 1.2,
    toneDiffLimit: 0.15,
    gradientThreshold: 0.12,
    edgeTaper: 0.35,
    maxBright: 0.96,
    maxLinksPerDot: 2,
    contrast: 1.12,
    quantizeLevels: 0,
    stippleJitter: 0.55,
    halftoneGamma: 0.8,
    edgeMag: 0.14,
  },

  organic_dither_dark_links21: {
    label: "Dark Links 21",
    renderStyle: "organic",
    gridCount: 42,
    minRadius: 2,
    maxRadius: 14,
    bridgeScale: 4.7,
    bridgeWaist: 0.07,
    maxConnectDist: 1.1,
    toneDiffLimit: 0.1,
    gradientThreshold: 0.09,
    edgeTaper: 0.24,
    maxBright: 0.38,
    maxLinksPerDot: 4,
    contrast: 1.14,
    quantizeLevels: 0,
  },

  organic_dither_blob_field: {
    label: "Dense Stipple",
    renderStyle: "stipple",
    gridCount: 48,
    minRadius: 1.5,
    maxRadius: 20,
    contrast: 0.98,
    stippleJitter: 0.62,
    halftoneGamma: 0.72,
  },

  grid_dither_refined: {
    label: "Fine Halftone Grid",
    renderStyle: "halftone",
    gridCount: 104,
    minRadius: 0.5,
    maxRadius: 11,
    contrast: 1.08,
    halftoneGamma: 0.8,
  },

  floyd_steinberg: {
    label: "Floyd–Steinberg (Classic Diffusion)",
    renderStyle: "fs",
    gridCount: 140,
    contrast: 1.05,
    quantizeLevels: 2,
    halftoneGamma: 1,
    edgeTaper: 0,
  },

  organic_grid_gradient: {
    label: "Halftone + Edge Lines",
    renderStyle: "halftone_edges",
    gridCount: 64,
    minRadius: 0.5,
    maxRadius: 14,
    contrast: 1.05,
    halftoneGamma: 0.86,
    edgeMag: 0.11,
  },

  grid_connected_dither: {
    label: "Halftone Screen",
    renderStyle: "halftone",
    gridCount: 72,
    minRadius: 0.5,
    maxRadius: 13,
    contrast: 1.02,
    halftoneGamma: 0.85,
  },

  jarvis_judice_ninke: {
    label: "Jarvis–Judice–Ninke",
    renderStyle: "jarvis",
    gridCount: 140,
    contrast: 1.0,
    quantizeLevels: 2,
    halftoneGamma: 1,
    edgeTaper: 0,
  },

  large_blob_dither_output: {
    label: "Large Organic + Bridges",
    renderStyle: "organic",
    gridCount: 22,
    minRadius: 6,
    maxRadius: 28,
    bridgeScale: 5.2,
    bridgeWaist: 0.2,
    maxConnectDist: 1.55,
    toneDiffLimit: 0.2,
    gradientThreshold: 0.065,
    edgeTaper: 0.48,
    maxBright: 0.55,
    maxLinksPerDot: 3,
    contrast: 1,
    quantizeLevels: 0,
  },

  organic_flow_dots: {
    label: "Loose Stipple",
    renderStyle: "stipple",
    gridCount: 36,
    minRadius: 4,
    maxRadius: 24,
    contrast: 1,
    stippleJitter: 0.48,
    halftoneGamma: 0.78,
  },

  organic_natural_connections: {
    label: "Organic + Bridges",
    renderStyle: "organic",
    gridCount: 50,
    minRadius: 2,
    maxRadius: 15,
    bridgeScale: 1.2 * Math.PI,
    bridgeWaist: 0.1,
    maxConnectDist: 1.2,
    toneDiffLimit: 0.15,
    gradientThreshold: 0.12,
    edgeTaper: 0.3,
    maxBright: 0.5,
    maxLinksPerDot: 4,
    contrast: 1,
    quantizeLevels: 0,
  },

  organic_circular_dither: {
    label: "Rounded Bridges",
    renderStyle: "organic",
    gridCount: 50,
    minRadius: 2,
    maxRadius: 16,
    bridgeScale: 3.2,
    bridgeWaist: 0.22,
    maxConnectDist: 1.12,
    toneDiffLimit: 0.14,
    gradientThreshold: 0.1,
    edgeTaper: 0.42,
    maxBright: 0.5,
    maxLinksPerDot: 4,
    contrast: 1,
    quantizeLevels: 0,
  },

  sierra2: {
    label: "Sierra-2",
    renderStyle: "sierra2",
    gridCount: 140,
    contrast: 1.0,
    quantizeLevels: 2,
    halftoneGamma: 1,
    edgeTaper: 0,
  },

  organic_dither_field_final: {
    label: "Stipple Field",
    renderStyle: "stipple",
    gridCount: 46,
    minRadius: 1.5,
    maxRadius: 19,
    contrast: 1.05,
    stippleJitter: 0.58,
    halftoneGamma: 0.74,
  },

  stucki: {
    label: "Stucki",
    renderStyle: "stucki",
    gridCount: 140,
    contrast: 1.0,
    quantizeLevels: 2,
    halftoneGamma: 1,
    edgeTaper: 0,
  },

  threshold_dither: {
    label: "Flat 1-Bit",
    renderStyle: "threshold",
    threshold: 0.48,
    contrast: 1,
  },

  organic_dither_spacing: {
    label: "Wide Bridge Reach",
    renderStyle: "organic",
    gridCount: 46,
    minRadius: 2,
    maxRadius: 15,
    bridgeScale: 3.6,
    bridgeWaist: 0.1,
    maxConnectDist: 1.65,
    toneDiffLimit: 0.2,
    gradientThreshold: 0.09,
    edgeTaper: 0.38,
    maxBright: 0.52,
    maxLinksPerDot: 4,
    contrast: 1,
    quantizeLevels: 0,
  },
};
